### ISSUE TITLE
Blog页面的加载滑入效果如何实现？

### ISSUE THREAD

**Issue by link9596** [kitian616/kitian616.github.io#1]
主题很不错，已Star，想请教一下你的主题页面加载完成后的渐变+滑入效果是如何实现的？

**Comment by kitian616** [comment]
https://github.com/kitian616/jekyll-TeXt-theme/blob/master/_sass/blog/_layout.default.scss#L6
https://github.com/kitian616/jekyll-TeXt-theme/blob/master/_sass/base/_animate.scss#L10
