### ISSUE TITLE
请问用LeanCloud实现页面流量统计的细节

### ISSUE THREAD

**Issue by FreeApe** [kitian616/kitian616.github.io#2]
1. 注册LeanCloud账号
2. 创建一个应用，名字随意
3. 在该应用下创建一个Class： Counter
4. 然后复制APP ID和APP Key以及Class名称Counter到_config.yml
这样就可以了吗？ 需要设置Counter的字段名称吗？

**Comment by kitian616** [comment]
不需要，不过得留意下权限，在控制台的 设置 -> 风险监测里可以看到。

后续请到 [Jekyll TeXt Theme](https://github.com/kitian616/jekyll-TeXt-theme) 里提 Issue。

## LeanCloud 设置流程

Register LeanCloud --> 创建应用 --> 创建 Class --> 「设置 -> 风险监测」 项里确保相应 Class 的 find 和 update 是所有人可操作的 --> 在「设置 -> 应用Key」项里得到 App ID 和 App Key --> 填写到 _config.yml 中

**Comment by FreeApe** [comment]
嗯，不知道什么原因，今天早上Class写入才生效，有延迟？ 另外创建的Class的ACL写权限默认是false的，这个需要自己改成true。
